type Habit {
    title: String
    metric: String
    note: String
    points: Int
    entry: Entry
}

type Entry {
    date: Date!
    tracker: [Habit!]
}

type Query {
    allHabits: [Habit!]
    allEntries: [Habit!]
}
